name: Run Unit Tests

on:
  pull_request:
  workflow_dispatch:
  push:

jobs:
  unit-test:
    name: Run tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: "18"
      - name: Install dependencies
        run: npm install
        working-directory: ./api
      - name: Run tests
        run: npm run test -- --detectOpenHandles
        working-directory: ./api